//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class ltcourierfee
    {
        public int WeightID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public Nullable<int> StartKg { get; set; }
        public Nullable<int> EndKg { get; set; }
        public Nullable<decimal> Price { get; set; }
    }
}
