//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication5
{
    using System;
    using System.Collections.Generic;
    
    public partial class trinvoice
    {
        public int InvoiceNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
        public string InvoiceTo { get; set; }
        public string ShipTo { get; set; }
        public Nullable<int> SalesID { get; set; }
        public Nullable<int> CourierID { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public Nullable<decimal> CourierFee { get; set; }
    
        public virtual mscourier mscourier { get; set; }
        public virtual mspayment mspayment { get; set; }
        public virtual mssale mssale { get; set; }
        public virtual trinvoice trinvoice1 { get; set; }
        public virtual trinvoice trinvoice2 { get; set; }
        public virtual trinvoice trinvoice11 { get; set; }
        public virtual trinvoice trinvoice3 { get; set; }
    }
}
